# agent_config.yaml

name: art_valuation_agent
description: Simplified agent system: metadata extraction + valuation
version: "0.1.0"

entrypoint: "adk_entrypoint:register_agents"

env:
  - MONGO_URI: ${MONGO_URI}
  - DB_NAME: ${DB_NAME}
  - COLLECTION_NAME: ${COLLECTION_NAME}

agents:
  - module: agents.metadata_agent
    class: MetadataAgent
  - module: agents.valuation_agent
    class: ValuationAgent
